### ISSUE TITLE
Log in to VRM within docker container not working

### ISSUE THREAD

**Issue by mmaattppoo** [victronenergy/venus-docker-grafana#18]
As of 2021 10 01 logging into VRM within the docker-grafana container no longer works.

Is this related to an expired security certificate for the VRMAPI? If so, Victron please update the certificate(s) and/or provide instructions how to address this issue.

**Comment by mpvader** [comment]
Hi, I'll ask someone to look into this; thanks.

**Comment by UlrichThiess** [comment]
### It's an certificate issue

**Here is the corresponding console message:**

    [info] [vrm] Logging In 
  
    (node:1) UnhandledPromiseRejectionWarning: FetchError: request to https://vrmapi.victronenergy.com/v2/auth/login failed, reason: certificate has expired
     
        at ClientRequest.<anonymous> (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/node-fetch/lib/index.js:1455:11)
     
        at emitOne (events.js:116:13)
     
        at ClientRequest.emit (events.js:211:7)
     
        at TLSSocket.socketErrorListener (_http_client.js:401:9)
     
        at emitOne (events.js:116:13)
     
        at TLSSocket.emit (events.js:211:7)
     
        at emitErrorNT (internal/streams/destroy.js:73:8)
     
        at _combinedTickCallback (internal/process/next_tick.js:139:11)
     
        at process._tickCallback (internal/process/next_tick.js:181:9)
     
    (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
     
    (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**If you check from the machine with wget:**

    # wget https://vrmapi.victronenergy.com
    --2021-10-04 14:09:57--  https://vrmapi.victronenergy.com/
    Resolving vrmapi.victronenergy.com (vrmapi.victronenergy.com)... 3.127.228.28
    Connecting to vrmapi.victronenergy.com (vrmapi.victronenergy.com)|3.127.228.28|:443... connected.
    ERROR: The certificate of 'vrmapi.victronenergy.com' is not trusted.
    ERROR: The certificate of 'vrmapi.victronenergy.com' has expired.
    # wget --version
    GNU Wget 1.18 built on linux-gnu.

**If you check your certificate chain with ssllabs.com:**
![grafik](https://user-images.githubusercontent.com/79257887/135977352-3cce7ef5-8105-49eb-9989-1ecc3a90a73e.png)

**Read this:**
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Solution:**
Please use just a new certificate and test with ssllabs.com
https://www.ssllabs.com/ssltest/analyze.html?d=vrmapi.victronenergy.com&hideResults=on&clearCache=on

**Comment by emansom** [comment]
> **If you check from the machine with wget:**

Which machine specifically are you referring to? The container? In that case, it may be related to a out of date certificate authority trust list (ca-certificates package on most distro's). Check the output of `docker images` and validate the latest `venus-docker-grafana` image from six months ago is being used.

**Comment by mpvader** [comment]
Thanks @emansom.

So, the real problem is that there is a certificate, in the trust store, which is in the docker image itself, which has expired. I'll find out who can best check, and then probably update that docker image.

Meanwhile, we (temporarily) fixed it: the certificate on https://vrmapi.victronenergy.com/ was changed this morning to another one, that circumvents the issue by using a different provider and thus different chain. We'll change that back, to lets encrypt, most likely a year from now. Ie when the now purchased commercial ssl certificate expires.

**Comment by UlrichThiess** [comment]
Thanks @mpvader, your certificate change fixed it.

**Comment by mmaattppoo** [comment]
Awesome! Thank you @mpvader for the fix on Victron's end and @UlrichThiess for the detective work.

This community forum and Victron's support of their products, services, and experiments (like the docker image for using grafana and influxdb) is why I champion them every chance I get.

Thank you again @mpvader!

**Comment by xcyb0rg** [comment]
I guess the certificate for vrmapi.victronenergy.com has been recently updated again to use one issued by "Let's Encrypt", so the problem is back.

The issue stems from the fact that the Docker image has the expired DST_Root_CA_X3.crt certificate bundled in. And this one is being used when checking the vrmapi cert. But because the CA cert is expired, verification fails. What adds insult to injury is that Node does not use the system-provides CA certs, but comes with its own bundled cert store. And, of course, the expired cert is there as well.

I hacked things around like this:

1. updated the docker-compose.yaml file and added the following line under the server section:

`command: "node --use-openssl-ca /usr/local/bin/venus-server --external-upnp"`

This is needed to tell Node to not use the bundled CA store, but the system one.

2. ran `docker-compose up --detach` to start root_server_1 with the new command line.

3. ran the following command to exclude the problematic cert from the system store:
`docker exec root_server_1 /bin/bash -c 'sed -i.orig -re "s/^.*DST_Root_CA_X3.crt/!&/" /etc/ca-certificates.conf && update-ca-certificates'`

4. restarted root_server_1:
`docker restart root_server_1`

Of course, the proper solution would be to have an updated docker image for venus-docker-server with the problematic CA cert removed.

**Comment by mman** [comment]
@xcyb0rg The official docker image for `venus-server` is way too old, and your fix is probably the easiest.

Work in progress on updating all the necessary dependencies, including node, and docker base image has been carried over the past months in this pull request: https://github.com/victronenergy/venus-docker-grafana-images/pull/22. You can use that branch to build fresh docker images with all dependencies updated.

But better, I am working on migration of existing `venus-server` and `venus-grafana-images` into https://github.com/victronenergy/venus-influx-loader, and https://github.com/victronenergy/venus-grafana-dashboards.

Official docker images of these two new repositories will be published and updated regularly during the next months, and that will deprecate the use of existing `venus-server`.

**Comment by mman** [comment]
Please try with https://github.com/victronenergy/venus-influx-loader and re-open if you still see issues. Closing here. @dirkjanfaber please close this issue.
