### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by e404nothing** [victronenergy/venus-docker-grafana#21]
I am trying to install this on a raspberry pi 4, and after cloning it into the pi, and running `docker-compose up --detach`,  I got this error:

```
Pulling upnp (victronenergy/venus-docker-upnp:latest)...
latest: Pulling from victronenergy/venus-docker-upnp
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by mman** [comment]
@e404nothing This is because your RPI 4 runs 64bit linux.

Unfortunately the original Venus Docker Grafana project never produced docker image for `linux/arm64`. Only 32bit `linux/armv7` and 64bit intel based `linux/amd64`, which were the only systems available at that time.

Please take a look at the new successor projects at https://github.com/victronenergy/venus-influx-loader and https://github.com/mman/venus-grafana-dashboards.

This is an update and work in progress of the original code, fixing all known bugs, updating all dependencies, and providing out of the box experience for all newly supported systems, including 32bit/64bit ARM, and 64bit Intel machines.

At the moment pre-built docker images are available in my personal docker hub repo, and will soon be available in the victronenergy docker hub repo as well... please stay tuned.

For now feel free to use the `:main` tagged images available here:

https://hub.docker.com/repository/docker/sodaengine/venus-influx-loader/tags?page=1&ordering=last_updated
https://hub.docker.com/repository/docker/sodaengine/venus-grafana/tags?page=1&ordering=last_updated

Questions and suggestions here please, thanks Martin!

**Comment by mman** [comment]
Will be addressed by publishing new docker images from https://github.com/victronenergy/venus-grafana/ and https://github.com/victronenergy/venus-influx-loader. Closing here, feel free to reopen against new repos if you see any issues. @dirkjanfaber please close this issue.
